### ISSUE TITLE
Refining/improving search feature

### ISSUE THREAD

**Issue by matt-curtis** [BohemianCoding/developer.sketchapp.com#14]
This is an awesome feature guys, thanks for the work put in! It makes traversing the documentation much, much easier :)

Quick thoughts / suggestions:
- Sometimes fails (?) to match properly, i.e. `ImageCollection` doesn't bring up `MSImageCollection`
- Add keyboard up/down/enter mapping to list items (see Github's Find File feature, etc.)
- Indicator in list whether match is in title (yellow highlight?), content, or both
- Show result count minimistically somewhere

**Comment by bomberstudios** [comment]
> This is an awesome feature guys, thanks for the work put in! It makes traversing the documentation much, much easier :)

Thank you for the kind words, we're pretty happy about how it turned out. 

> Sometimes fails (?) to match properly, i.e. ImageCollection doesn't bring up MSImageCollection

The system we're using (lunr.js) doesn't support substring searching : (

I've filed an issue about that at https://github.com/olivernn/lunr.js/issues/193

> Add keyboard up/down/enter mapping to list items (see Github's Find File feature, etc.)

I believe we have some work done in this direction. Ping @intemperie : )

> Indicator in list whether match is in title (yellow highlight?), content, or both

I think I can do this.

> Show result count minimistically somewhere

Makes sense. Again, this is something for @intemperie

**Comment by intemperie** [comment]
Will take a look to these. Thanks, @matt-curtis! :)

**Comment by jasonkylefrank** [comment]
Hi guys. I'm curious about the state of search in general now.  As of today, it seems to **not find any pages**:

![image](https://user-images.githubusercontent.com/7502365/36064031-02ff7a92-0e53-11e8-8634-7455f3338347.png)


![image](https://user-images.githubusercontent.com/7502365/36064036-0fc468b4-0e53-11e8-9f53-7d41259db061.png)

Should I file a new issue for this?

**Comment by intemperie** [comment]
Hello,

Thank you for contacting us.

Would you send this inquire to our plugin developers page? It's here: www.sketchplugins.com

We're gathering the developers community there in order to create a more efficient feedback system.

Best,


—
Jorge Fernández
Customer Support at Sketch
www.sketchapp.com

--- original message ---
On Sat, Feb 10, 2018 at 05:11 pm, <notifications@github.com> Jason K Frank wrote:


Hi guys. I'm curious about the state of search in general now. As of today, it seems to not find any pages:



Should I file a new issue for this?

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by mathieudutour** [comment]
With the new API documentation, I changed this to use the search from [slate](https://github.com/lord/slate) so hopefully it will work a bit better
