### ISSUE TITLE
Event System

### ISSUE THREAD

**Issue by matt-curtis** [BohemianCoding/developer.sketchapp.com#5]
From trawling through the headers, I know there exists a delegation system, but does there exist a global event/notification system? NSNotifications or otherwise? For example: when the selection or current document changes...

**Comment by bomberstudios** [comment]
AFAIK, nothing that could be easily used by Plugins. We'd like to improve this in the future, since triggering scripts in response to app events is something that would really take Sketch Plugins to the next level : )

**Comment by samdeane** [comment]
Yeah, I think in an ideal world we would want to provide a public mechanism for this - so that plugins can hook into various events. It's on our map (but it's a big map).

In the meantime there isn't a single unified "private" mechanism unfortunately (if there had been, we'd probably have done the public one by now).

**Comment by alanhamlett** [comment]
Any ETA on app-triggered events? It's preventing the creation of a [WakaTime](https://wakatime.com) plugin.

**Comment by samdeane** [comment]
I'm afraid that it's not likely to be imminent. It requires a few architectural changes internally, which are competing for the time with a lot of other things!

**Comment by mathieudutour** [comment]
plugins can now listen to `actions`: http://sketchplugins.com/d/70-using-the-action-api
