### ISSUE TITLE
how can i write a plugin?

### ISSUE THREAD

**Issue by tcdona** [BohemianCoding/developer.sketchapp.com#87]
http://developer.sketchapp.com/
the document in the video seems to be removed.（eg. MSLayer ...）

http://developer.sketchapp.com/reference/api/class/api/Rectangle.js~Rectangle.html
i have no idea how to use them, there isn't even a example for jsapi.
http://developer.sketchapp.com/reference/action/ [nothing!]

if we want to write a plugin like CSSketch/Craft 。。。
that means we must learn Appkit/Foundation , this is the only way ?

http://developer.sketchapp.com/reference/api/
there is error when running :
```
var sketch = context.api()

log(sketch.api_version)
log(sketch.version)
log(sketch.build)
log(sketch.full_version)


var document = sketch.selectedDocument;
var selection = document.selectedLayers;
var page = document.selectedPage;

var group = page.newGroup({frame: new sketch.Rectangle(0, 0, 100, 100), name:"Test"});
var rect = group.newShape({frame: new sketch.Rectangle(10, 10, 80, 80)});

log(selection.isEmpty);
selection.iterate(function(item) { log(item.name); } );

selection.clear();
log(selection.isEmpty);

group.select();
rect.addToSelection();

sketch.getStringFromUser("Test", "default");
sketch.getSelectionFromUser("Test", ["One", "Two"], 1);
sketch.message("Hello mum!");
sketch.alert("Title", "message");
```

```
1.1
40
33762
40 (33762)
TypeError: undefined is not a constructor (evaluating 'new sketch.Rectangle(0, 0, 100, 100)')
line: 19
sourceURL: /Users/tcmac/.atom/packages/sketchapp-scripter/scripting/run.sketchplugin
column: 55
stack: onRun@/Users/tcmac/.atom/packages/sketchapp-scripter/scripting/run.sketchplugin:19:55
```

and there is wrong with example code too
https://github.com/BohemianCoding/SketchAPI/issues/47

so, how can we make a plugin, the easy way?

**Comment by samdeane** [comment]
Sorry, you are right - the documentation is lagging badly behind at the moment. Not enough hours in the day...

I’ve just tried the script example you pasted above, and it is working in Sketch 41.2 (and should work in later versions). From the log you posted, you’re running v40 - it’s possible that the API syntax has been tweaked since then. It’s intended that the API not change, but it is currently still under development.

Have you looked at the example plugins: http://developer.sketchapp.com/examples/ ?
