### ISSUE TITLE
No symbols support in the new API

### ISSUE THREAD

**Issue by emilienh** [BohemianCoding/developer.sketchapp.com#96]
Layers embedded in symbols aren't reachable when browsing the layer hierarchy with the new API.

**Comment by samdeane** [comment]
That’s sort of by design - you wouldn’t want a script to be manipulating the layers inside the symbol, thinking that they were just manipulating normal layers, it could get messy...

We probably do need a simple way to resolve the symbol link though, so that you can track through to the layers in it somehow.

It is complicated by the fact that symbols can contain sub-symbols.

We do actually expand symbol instances out into temporary hierarchies of real layer objects, but we do that transparently during rendering (and then cache them). That’s not really something we can expose to scripts.

This needs thinking about a bit :)

**Comment by emilienh** [comment]
Thanks for the explanation! We ended up just using legacy APIs to do this, it works for now.

**Comment by samdeane** [comment]
Cool - glad you got something working. If you’ve got any plugin code that you want to share, so that we can see exactly what you’re doing with/to the symbol layers, that would be handy. We can then try to generalise something to add to the api which covers that as well as any other use cases we think of.

Don’t worry if it’s not shareable though :)

**Comment by emilienh** [comment]
No problem! The plugin I am working on is [Smartling](https://github.com/Smartling/smartling-sketch-plugin). The purpose is to traverse the entire document to get all strings from text layers. We can then translate those strings and display them in a copy of the original Sketch page. 

I understand why it would be a disaster to mess with symbol layers, that's why our plugin extracts all layers from symbols for the translated page.

[This](https://github.com/Smartling/smartling-sketch-plugin/blob/master/Smartling.sketchplugin/Contents/Sketch/strings.js#L236) is where we traverse all symbols using legacy APIs and get their strings, and [here](https://github.com/Smartling/smartling-sketch-plugin/blob/master/Smartling.sketchplugin/Contents/Sketch/strings.js#L289) is where we convert symbols into regular groups for the translated page. 

Thanks for your help!

**Comment by tompiarulli** [comment]
I can't think of any use cases where you would want to manipulate layers inside of symbols but there are a lot of use cases for being able to traverse those layers in a read-only fashion. I imagine tools that generate design specs (Invision Inspect for example) wouldn't work properly if symbols are a black box that you can't traverse.

I'm new to the Sketch API so there may be solutions I'm not aware of but I'm working with a plugin right now to convert layers in Sketch to layers in Framer for rapid prototyping but all the plugin can give me when it encounters a symbol is an empty layer with the dimensions so that kind of breaks the workflow.

**Comment by santiagoaguiar** [comment]
We are also developing a plugin that needs this functionality to traverse the symbol layer hierarchy to export each layer as an image. If we do that from the symbol definition, we lose the overrides and sizing. Is there any other way to do this?
